---
title: "Downloading ctd Data"
author: "Dan Kelley (https://orcid.org/0000-0001-7808-5911)"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
    fig_caption: yes
    fig_width: 3.5
    fig_height: 3.5
    dpi: 72
    dev.args: list(pointsize=11)
vignette: >
  %\VignetteIndexEntry{Downloading ctd Data}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  markdown:
    wrap: 72
---

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

The function `dod.ctd()` can download ctd data from the Bedford Basin Mooring
Program (BBMP), Bermuda Atlantic Time Series (BATS), Global Temperature and
Salinity Program (GTSPP) etc by calling their respective functions
`dod.ctd.bbmp()`, `dod.ctd.bats()` or `dod.ctd.tspp()`.

These functions vary slightly in detail, because the data servers vary.

For example, in `dod.ctd.bbmp()` the `ID` parameter is the desired file from
the index. These files have names that fit a convention used at the Bedford
Institute of Oceanography.  The example in the README file for this repository
shows how to discover the file names.

The `ID` parameter of `dod.gtspp()` takes a different form. For example,
`ID="at202401"` indicates data for the Atlantic ocean (first 2 characters)
acquired in the year 2024 (next 4 characters) and in January (last 2
characters).
